"""This code defines a Django model for a collaboration room."""
from django.db import models

class CollaborationRoom(models.Model):
    """Defines a model named CollaborationRoom that inherits from models.Model, making it a Django model that will be mapped to a database table."""
    # A variable to store the name of the collaboration room.
    # Specifies that this field is a character field with a maximum length of 255 characters. 
    # The unique=True parameter ensures that each room name is unique across the database, preventing duplicate room names.
    name = models.CharField(max_length=255, unique=True) 
    # A field to store the timestamp when the collaboration room was created.
    # Automatically sets the field to the current date and time when a new CollaborationRoom instance is created. 
    # This is useful for keeping track of when each collaboration room was added to the database.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        """
        Return the string representation of the CollaborationRoom, which is its name.

        Input: None
        Output: str
        """
        return self.name

""" 
    After this code section is implemented 
        python manage.py makemigrations
            This command looks at the models.py file in each installed Django app and creates new migrations based on the changes made to models.
            It generates migration files in the migrations directory of the app. 
            These files contain the SQL commands needed to update the apps database schema.
            Essentially, it turns the model definitions into a series of database operations
        python manage.py migrate
            This command applies the migrations generated by makemigrations to the database.
            It reads the migration files and executes the necessary SQL commands to update the apps database schema.
            This includes creating tables, adding fields, changing field types, and other database schema modifications as defined in the models.


    are run. These are key steps in Django to create and apply database migrations based on your models.
"""